[general]
import = [
    "~/.config/alacritty/alacritty-theme.toml"
]

[window]
# Removes all window decorations (titlebar, borders)
# decorations = "None"
opacity = 1
decorations = "Full"

# opacity = 0.5

[window.padding]
x = 0
y = 0

[scrolling]
history = 4000

[font]
size = 14.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = "Block"


